import { useState } from 'react';
import { Leaderboard } from './components/Leaderboard';
import { SkillExplorer } from './components/SkillExplorer';
import { AuditSandbox } from './components/AuditSandbox';
import { SkillDetailModal } from './components/SkillDetailModal';
import { auditSkill } from '@skillgauge/core';


// Load static bundle data generated by scripts/sync-skills.js
import leaderboardData from './data/leaderboard.json';
import skillsData from './data/skills-bundle.json';

interface LeaderboardSkill {
  name: string;
  repository: string;
  hash: string;
  author: string;
  tier: 'Tier 1' | 'Tier 2' | 'Tier 3';
  overallScore: number;
  submittedAt: string;
}

interface SkillFile {
  name: string;
  path: string;
  content: string;
}

function App() {
  const [activeTab, setActiveTab] = useState<'leaderboard' | 'explorer' | 'sandbox'>('leaderboard');
  const [selectedSkillKey, setSelectedSkillKey] = useState<string | null>(null);
  
  // Custom sandbox audit result display in the same modal
  const [sandboxReport, setSandboxReport] = useState<any | null>(null);
  const [sandboxContent, setSandboxContent] = useState<string>('');

  const leaderboardSkills = (leaderboardData as { skills: LeaderboardSkill[] }).skills;
  const localSkills = skillsData as { [key: string]: SkillFile };
  const localKeys = Object.keys(localSkills);

  const selectedLocalSkill = selectedSkillKey ? localSkills[selectedSkillKey] : null;
  
  // Dynamically compute report for selected local skill
  let activeReport: any = null;
  let activeContent = '';
  let activeName = '';

  if (selectedLocalSkill) {
    try {
      activeReport = auditSkill(selectedLocalSkill.content);
      activeContent = selectedLocalSkill.content;
      activeName = selectedSkillKey!;
    } catch (err) {
      console.error('Failed to audit local skill', err);
    }
  } else if (sandboxReport) {
    activeReport = sandboxReport;
    activeContent = sandboxContent;
    activeName = sandboxReport.name || 'Sandbox Input';
  }

  const handleShowSandboxResult = (report: any, content: string) => {
    setSandboxReport(report);
    setSandboxContent(content);
  };

  const handleCloseModal = () => {
    setSelectedSkillKey(null);
    setSandboxReport(null);
  };

  return (
    <>
      {/* Background Mesh Glows */}
      <div className="glow-orb glow-orb-purple" />
      <div className="glow-orb glow-orb-emerald" />

      <div className="app-container">
        {/* Floating Nav Pill */}
        <header className="floating-nav">
          <div className="nav-logo">
            <img src="/favicon.png" alt="SkillGauge Logo" style={{ width: '24px', height: '24px', borderRadius: '4px', objectFit: 'cover', mixBlendMode: 'screen' }} /> SkillGauge
          </div>
          <nav className="nav-links">
            <button
              className={`nav-link ${activeTab === 'leaderboard' ? 'active' : ''}`}
              onClick={() => setActiveTab('leaderboard')}
            >
              Leaderboard
            </button>
            <button
              className={`nav-link ${activeTab === 'explorer' ? 'active' : ''}`}
              onClick={() => setActiveTab('explorer')}
            >
              Local Skills
            </button>
            <button
              className={`nav-link ${activeTab === 'sandbox' ? 'active' : ''}`}
              onClick={() => setActiveTab('sandbox')}
            >
              Sandbox Auditor
            </button>
          </nav>
        </header>

        {/* Hero Section */}
        <section className="hero-section">
          <div className="eyebrow">Scientific Auditor System</div>
          <h1 className="hero-title">
            Optimize Your Agent <span>Skills & Prompts</span>
          </h1>
          <p className="hero-subtitle">
            A static analysis suite and evaluation engine testing process instructions against a strict 100-criteria scientific matrix.
          </p>
        </section>

        {/* Main Tab Contents */}
        <main style={{ flexGrow: 1, zIndex: 10, display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          {activeTab === 'leaderboard' && (
            <div style={{ width: '100%', animation: 'fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1)' }}>
              <Leaderboard
                skills={leaderboardSkills}
                localKeys={localKeys}
                onSelectSkill={(key) => setSelectedSkillKey(key)}
              />
            </div>
          )}

          {activeTab === 'explorer' && (
            <div style={{ width: '100%', animation: 'fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1)' }}>
              <SkillExplorer
                skills={localSkills}
                onSelectSkill={(key) => setSelectedSkillKey(key)}
              />
            </div>
          )}

          {activeTab === 'sandbox' && (
            <div style={{ width: '100%', animation: 'fadeUp 0.6s cubic-bezier(0.16, 1, 0.3, 1)' }}>
              <AuditSandbox
                onShowResult={handleShowSandboxResult}
              />
            </div>
          )}
        </main>

        {/* Detail Analysis Modal */}
        {(selectedSkillKey || sandboxReport) && (
          <SkillDetailModal
            report={activeReport}
            skillName={activeName}
            content={activeContent}
            onClose={handleCloseModal}
          />
        )}

        {/* Footer */}
        <footer style={{
          padding: '40px 0 24px',
          borderTop: '1px solid var(--border-muted)',
          color: 'var(--text-muted)',
          fontSize: '12px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginTop: 'auto',
          flexWrap: 'wrap',
          gap: '16px'
        }}>
          <div>© 2026 SkillGauge Monorepo. All rights reserved.</div>
          <div style={{ display: 'flex', gap: '16px' }}>
            <a href="https://github.com/ThanhNguyxnOrg/SkillGauge" target="_blank" rel="noopener noreferrer" style={{ color: 'inherit', textDecoration: 'none' }}>GitHub Repository</a>
            <span>•</span>
            <span>Scientific Specification v1.0</span>
          </div>
        </footer>
      </div>
    </>
  );
}

export default App;
